# Generated by Django 5.0.3 on 2024-03-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0005_alter_notification_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('Like', 'Like'), ('Comment', 'Comment'), ('Follow', 'Follow'), ('Message', 'Message')], max_length=10),
        ),
    ]
